### ISSUE TITLE
Sample not working

### ISSUE THREAD

**Issue by omidp** [behsa-oss/ganjex#1]
After I send a GET request to http://localhost:8080/helloworld/hello, I receive following error :

Failed to read HTTP message: org.springframework.http.converter.HttpMessageNotReadableException: Required request body is missing: public org.springframework.http.ResponseEntity<?> com.sample.controller.Dispatcher.dispatch(java.lang.String,java.lang.String,java.util.Map<java.lang.String, java.lang.Object>)

which is cause by missing request body due to @RequestBody AFAIK you can not send request body with GET Request, can you ?

After I send a POST request with empty body to http://localhost:8080/helloworld/hello, I receive following error :

java.lang.IllegalStateException which doesn't say much about what is happening.

I'm using defualt configuration + eclipse + eclipse maven resulotion workspace and run  SampleFramework.java (Spring boot).

**Comment by isahekmat** [comment]
method get of the ServiceContainer class show IllegalStateException is thrown when the system does not find any module to process the request,  Are you sure you deploy the 'helloworld' module by copy the jar file into service directory? can you share the log?

**Comment by omidp** [comment]
When I try to build web-sample-framework I get this : 

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (checkstyle-validation) on project web-sample-framework: Failed during checkstyle execution: Unable to find suppressions file at location: src/checkstyle/checkstyle-suppressions.xml: Could not find resource 'src/checkstyle/checkstyle-suppressions.xml'`

besides I realize the target version is 1.9, does it work with 1.8 I'm using JDK 1.8 ?

**Comment by isahekmat** [comment]
You're right, That was a minor bug, I fixed that, pull and retry again,
I also changed the java version to 1.8

**Comment by omidp** [comment]
After I copied web-sample-service-hello-1.0-SNAPSHOT.jar to services directory, by sending a POST request to http://localhost:8080/helloworld/hello with body 

`{
"name": "world"
}`

it is working. 

Since it is only working with jar files I think it might be a good idea to add classpath scanning instead of jar scanning .

**Comment by isahekmat** [comment]
Don't hesitate to contribute, you can work on classpath scanning, I would be glad to accept such a pull request
