### ISSUE TITLE
Tweet analyzer sample

### ISSUE THREAD

**Issue by isahekmat** [behsa-oss/ganjex#6]
It's suggestion for a sample application. It should be created in the sample directory.

There is a use case of Ganjex when you want to handle different strategies, and these strategies changed frequently, for example, using Ganjex we can write a tweet analyzing platform which analyzers can be added or removed from it in runtime. Assume this platform should analyze different hashtags and each hashtag has it's own analyzer, for example, we want to count the tweets of a hashtag in each day, and we want the sum of word-count of tweets with some other hashtag and so on, This strategies changed frequently and we don't want to restart our application to deploy a new strategy.

In this example Ganjex services can act as analyzers, each hashtag can have its own analyzers, so each service should define which hashtag they suppose to analyze.

If you need help or it's still unclear, ask here.

**Comment by akarimin** [comment]
:+1:
